authors:
  - affiliation: DNA Data Bank of Japan
    github_account: ddbj
    name: ddbj-workflow
  - affiliation: The University of Tokyo
    github_account: suecharo
    name: Hirotaka Suetake
    orcid: 0000-0003-2765-0049
  - affiliation: National Institute of Genetics
    github_account: tom-tan
    name: Tomoya Tanjo
    orcid: 0000-0002-4421-9659
  - affiliation: Database Center for Life Science
    github_account: inutano
    name: Tazro Ohta
    orcid: 0000-0003-3777-5945
  - affiliation: Osaka University
    github_account: yyoshiaki
    name: Yoshiaki Yasumizu
    orcid: 0000-0002-9872-4909
  - github_account: ykohki
id: a74efdc3-6205-4b06-82e0-9aa54238268f
license: Apache-2.0
version: 1.0.0
workflow:
  files:
    - target: deepTools_computeMatrix_reference-point.cwl
      type: primary
      url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/tool/deepTools/deepTools_computeMatrix_reference-point/deepTools_computeMatrix_reference-point.cwl
  language:
    type: CWL
    version: v1.0
  name: "DAT2-cwl workflow - deepTools_computeMatrix_reference-point"
  readme: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/README.md
  testing:
    - files:
        - target: test-job.yml
          type: wf_params
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/tool/deepTools/deepTools_computeMatrix_reference-point/test-job.yml
      id: test
