authors:
  - affiliation: DNA Data Bank of Japan
    github_account: ddbj
    name: ddbj-workflow
  - affiliation: The University of Tokyo
    github_account: suecharo
    name: Suetake, Hirotaka
    orcid: 0000-0003-2765-0049
  - affiliation: National Institute of Genetics
    github_account: tom-tan
    name: Tanjo, Tomoya
    orcid: 0000-0002-4421-9659
  - affiliation: Database Center for Life Science
    github_account: inutano
    name: Ohta, Tazro
    orcid: 0000-0003-3777-5945
  - affiliation: Osaka University
    github_account: yyoshiaki
    name: Yasumizu, Yoshiaki
    orcid: 0000-0002-9872-4909
  - github_account: ykohki
    name: Yamada, Kohki
id: 37c3d481-d78b-4a5e-b6b0-ed902610d927
license: Apache-2.0
version: 1.0.0
workflow:
  files:
    - target: bismark.cwl
      type: primary
      url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/tool/bismark/bismark/bismark.cwl
  language:
    type: CWL
    version: v1.0
  name: "DAT2-cwl bismark"
  readme: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/README.md
  testing:
    - files:
        - target: test-job.yml
          type: wf_params
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/tool/bismark/bismark/test-job.yml
        - target: bismark/Bisulfite_Genome
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome
        - target: bismark/chr22.fa
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/chr22.fa
        - target: bismark/Bisulfite_Genome/GA_conversion
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/GA_conversion
        - target: bismark/Bisulfite_Genome/CT_conversion
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/CT_conversion
        - target: bismark/Bisulfite_Genome/GA_conversion/BS_GA.1.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/GA_conversion/BS_GA.1.bt2
        - target: bismark/Bisulfite_Genome/GA_conversion/BS_GA.2.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/GA_conversion/BS_GA.2.bt2
        - target: bismark/Bisulfite_Genome/GA_conversion/BS_GA.4.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/GA_conversion/BS_GA.4.bt2
        - target: bismark/Bisulfite_Genome/GA_conversion/BS_GA.rev.1.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/GA_conversion/BS_GA.rev.1.bt2
        - target: bismark/Bisulfite_Genome/GA_conversion/BS_GA.rev.2.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/GA_conversion/BS_GA.rev.2.bt2
        - target: bismark/Bisulfite_Genome/GA_conversion/BS_GA.3.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/GA_conversion/BS_GA.3.bt2
        - target: bismark/Bisulfite_Genome/GA_conversion/genome_mfa.GA_conversion.fa
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/GA_conversion/genome_mfa.GA_conversion.fa
        - target: bismark/Bisulfite_Genome/CT_conversion/genome_mfa.CT_conversion.fa
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/CT_conversion/genome_mfa.CT_conversion.fa
        - target: bismark/Bisulfite_Genome/CT_conversion/BS_CT.4.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/CT_conversion/BS_CT.4.bt2
        - target: bismark/Bisulfite_Genome/CT_conversion/BS_CT.rev.2.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/CT_conversion/BS_CT.rev.2.bt2
        - target: bismark/Bisulfite_Genome/CT_conversion/BS_CT.2.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/CT_conversion/BS_CT.2.bt2
        - target: bismark/Bisulfite_Genome/CT_conversion/BS_CT.1.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/CT_conversion/BS_CT.1.bt2
        - target: bismark/Bisulfite_Genome/CT_conversion/BS_CT.rev.1.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/CT_conversion/BS_CT.rev.1.bt2
        - target: bismark/Bisulfite_Genome/CT_conversion/BS_CT.3.bt2
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/bismark/Bisulfite_Genome/CT_conversion/BS_CT.3.bt2
        - target: DRR024501_1.fastq
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/DRR024501_1.fastq
      id: test
