authors:
  - affiliation: DNA Data Bank of Japan
    github_account: ddbj
    name: ddbj-workflow
  - affiliation: The University of Tokyo
    github_account: suecharo
    name: Suetake, Hirotaka
    orcid: 0000-0003-2765-0049
  - affiliation: National Institute of Genetics
    github_account: tom-tan
    name: Tanjo, Tomoya
    orcid: 0000-0002-4421-9659
  - affiliation: Database Center for Life Science
    github_account: inutano
    name: Ohta, Tazro
    orcid: 0000-0003-3777-5945
  - affiliation: Osaka University
    github_account: yyoshiaki
    name: Yasumizu, Yoshiaki
    orcid: 0000-0002-9872-4909
  - github_account: ykohki
    name: Yamada, Kohki
id: 9d04b71e-6ecd-4337-9c3c-1920582f5800
license: Apache-2.0
version: 1.0.0
workflow:
  files:
    - target: rsem_index.cwl
      type: primary
      url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/tool/rsem/rsem_index/rsem_index.cwl
  language:
    type: CWL
    version: v1.0
  name: "DAT2-cwl rsem_index"
  readme: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/README.md
  testing:
    - files:
        - target: test-job.yml
          type: wf_params
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/tool/rsem/rsem_index/test-job.yml
        - target: Homo_sapiens.GRCh38.95.chr22.gtf
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/Homo_sapiens.GRCh38.95.chr22.gtf
        - target: RSEM_reference/RSEM_reference.ti
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/RSEM_reference/RSEM_reference.ti
        - target: RSEM_reference/RSEM_reference.grp
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/RSEM_reference/RSEM_reference.grp
        - target: RSEM_reference/RSEM_reference.seq
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/RSEM_reference/RSEM_reference.seq
        - target: RSEM_reference/RSEM_reference.n2g.idx.fa
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/RSEM_reference/RSEM_reference.n2g.idx.fa
        - target: RSEM_reference/RSEM_reference.transcripts.fa
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/RSEM_reference/RSEM_reference.transcripts.fa
        - target: RSEM_reference/RSEM_reference.idx.fa
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/RSEM_reference/RSEM_reference.idx.fa
        - target: RSEM_reference/RSEM_reference.chrlist
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/RSEM_reference/RSEM_reference.chrlist
        - target: Homo_sapiens.GRCh38.dna.primary_assembly.chr22.fa
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/Homo_sapiens.GRCh38.dna.primary_assembly.chr22.fa
      id: test
