#!/bin/sh
set -eu

if [ $# -ne 1 ]; then
  echo "Usage: bash test.sh workflow_name"
  exit 1
fi

workflow_name=$1
script_dir=$(cd $(dirname $0) && pwd)
root_dir=$(cd ${script_dir}/.. && pwd)
workflow_root_dir=$(cd ${root_dir}/workflow && pwd)
workflow_dir=$(find ${workflow_root_dir} -type d | grep ${workflow_name})

echo "*** START BUILDING workflow: ${workflow_name} ***"
echo "...validate by cwlworkflow"
cwlworkflow --validate ${workflow_dir}/${workflow_name}.cwl

echo "...generate ${workflow_name}.yml"
cwlworkflow --make-template ${workflow_dir}/${workflow_name}.cwl > ${workflow_dir}/${workflow_name}.yml
cp ${workflow_dir}/${workflow_name}.yml ${root_dir}/test/workflow/test_job/

echo "*** FINISH BUILDING workflow: ${workflow_name} ***"
