#!/bin/sh
set -eu

if [ $# -ne 1 ]; then
  echo "Usage: bash test.sh workflow_name(test_workflow/test_workflow_1)"
  exit 1
fi

workflow_dir=${1}
workflow_name=$(echo ${workflow_dir} | sed -e 's/.*\///g')
script_dir=$(cd $(dirname $0) && pwd)
workflow_root_dir=$(cd ${script_dir}/../workflow && pwd)

echo "*** START PREPARING workflow TEMPLATE: ${workflow_name} ***"
echo "...making workflow dir"
mkdir -p "${workflow_root_dir}/${workflow_dir}"

echo "...generate ${workflow_name}.cwl"
cat << EOS > "${workflow_root_dir}/${workflow_dir}/${workflow_name}.cwl"
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: Workflow
doc: string
requirements: {}
inputs:
  input_1:
    type: string
steps:
  step-1:
    run: string
    in:
      input_1: input_1
    out:
      - output_1
outputs:
  step-1_output_1:
    type: File
    outputSource: step-1/output_1
EOS

echo "...generate ${workflow_name}.yml"
touch "${workflow_root_dir}/${workflow_dir}/${workflow_name}.yml"

echo "*** FINISH PREPARING workflow TEMPLATE: ${workflow_name} ***"
