authors:
  - affiliation: DNA Data Bank of Japan
    github_account: ddbj
    name: ddbj-workflow
  - affiliation: The University of Tokyo
    github_account: suecharo
    name: Hirotaka Suetake
    orcid: 0000-0003-2765-0049
  - affiliation: National Institute of Genetics
    github_account: tom-tan
    name: Tomoya Tanjo
    orcid: 0000-0002-4421-9659
  - affiliation: Database Center for Life Science
    github_account: inutano
    name: Tazro Ohta
    orcid: 0000-0003-3777-5945
  - affiliation: Osaka University
    github_account: yyoshiaki
    name: Yoshiaki Yasumizu
    orcid: 0000-0002-9872-4909
  - github_account: ykohki
id: bd6acbfe-d667-4e53-aacc-47282f818e0c
license: Apache-2.0
version: 1.0.0
workflow:
  files:
    - target: samtools-sort.cwl
      type: primary
      url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/tool/samtools/sort/samtools-sort.cwl
  language:
    type: CWL
    version: v1.0
  name: "DAT2-cwl workflow - samtools-sort"
  readme: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/README.md
  testing:
    - files:
        - target: test-job.yml
          type: wf_params
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/tool/samtools/sort/test-job.yml
        - target: ERR034597_1.bam
          type: other
          url: https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/main/test/data/ERR034597_1.bam
      id: test
