#!/bin/sh
set -eux

if [ $# -ne 1 ]; then
  echo "Usage: bash test.sh workflow_name"
  exit 1
fi

workflow_name=$1
test_dir=$(cd $(dirname $0) && pwd)
root_dir=$(cd ${test_dir}/../.. && pwd)
workflow_dir=$(find ${root_dir}/workflow -type d | grep ${workflow_name})

echo "*** TEST START: ${workflow_name} ***"
echo "...check workflow dir"
# workflow dir が存在するか
if [ ! -d ${workflow_dir} ]; then
  echo "[ERROR] ${workflow_dir} does not exist."
  exit 1
else
  echo "[PASS] workflow dir exists."
fi

cwl_file=${workflow_dir}/${workflow_name}.cwl

echo "...check cwl file"
# cwl file が存在するか
if [ ! -f ${cwl_file} ]; then
  echo "[ERROR] ${cwl_file} does not exist."
  exit 1
else
  echo "[PASS] cwlfile exists."
fi

echo "...validate by cwltool"
# cwltool の validation
cwltool --validate ${cwl_file}
if [ $? -ne 0 ]; then
  echo "[ERROR] cwltool validation is failed."
  exit 1
else
  echo "[PASS] cwltool validation is passed."
fi

# template を作成しておく
cwl_template_file=${workflow_dir}/${workflow_name}.yml
cwltool --make-template ${cwl_file} > ${cwl_template_file}

# test_job を使って、実際に実行する
echo "...do test job"
test_job_file=${test_dir}/test_job/${workflow_name}.yml
if [ ! -f ${test_job_file} ]; then
  echo "[ERROR] ${test_job_file} does not exist."
  exit 1
else
  echo "test job file exists."
fi
cwltool --outdir ${test_dir}/tmp ${cwl_file} ${test_job_file}
if [ $? -ne 0 ]; then
  echo "[ERROR] test job is failed."
  exit 1
else
  echo "[PASS] test job is passed."
fi
#rm -rf ${test_dir}/tmp

echo "*** ALL TEST IS PASSED ***"
